#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_HoldSummonRing

#include "Basic.hpp"

#include "ABPT_HoldItem_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_HoldSummonRing.ABP_HoldSummonRing_C
// 0x0000 (0x1130 - 0x1130)
class UABP_HoldSummonRing_C final : public UABPT_HoldItem_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_HoldSummonRing_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_HoldSummonRing_C")
	}
	static class UABP_HoldSummonRing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_HoldSummonRing_C>();
	}
};
DUMPER7_ASSERTS_UABP_HoldSummonRing_C;

SDK_NAMESPACE_END
