#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABPT_Menu_CockpitBase

#include "Basic.hpp"

#include "ABPT_Menu_CockpitBase_classes.hpp"
#include "ABPT_Menu_CockpitBase_parameters.hpp"


SDK_NAMESPACE_START

// Function ABPT_Menu_CockpitBase.ABPT_Menu_CockpitBase_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABPT_Menu_CockpitBase_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPT_Menu_CockpitBase_C", "AnimGraph");

	Params::ABPT_Menu_CockpitBase_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABPT_Menu_CockpitBase.ABPT_Menu_CockpitBase_C.ExecuteUbergraph_ABPT_Menu_CockpitBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABPT_Menu_CockpitBase_C::ExecuteUbergraph_ABPT_Menu_CockpitBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABPT_Menu_CockpitBase_C", "ExecuteUbergraph_ABPT_Menu_CockpitBase");

	Params::ABPT_Menu_CockpitBase_C_ExecuteUbergraph_ABPT_Menu_CockpitBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
