#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Drone

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Drone.BP_Drone_C
// 0x0050 (0x0430 - 0x03E0)
class ABP_Drone_C final : public ADrone
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         IdleMove_Curve_DroneIdle_22058D284A4524C5F98EB4986F794A3E; // 0x03E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         IdleMove_PosYRatio_22058D284A4524C5F98EB4986F794A3E; // 0x03EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            IdleMove__Direction_22058D284A4524C5F98EB4986F794A3E; // 0x03F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F1[0x7];                                      // 0x03F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     IdleMove;                                          // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Rotation_6FFD93554112DE5A9819B4B3F957D58D; // 0x0400(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Curve_DroneInOutRot_6FFD93554112DE5A9819B4B3F957D58D; // 0x0404(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Curve_DroneInOutRot_6FFD93554112DE5A9819B4B3F957D58D_0; // 0x0408(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Curve_DroneInOutRot_6FFD93554112DE5A9819B4B3F957D58D_1; // 0x040C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Curve_DroneInOut_6FFD93554112DE5A9819B4B3F957D58D; // 0x0410(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DroneInOut_Position_6FFD93554112DE5A9819B4B3F957D58D; // 0x0414(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            DroneInOut__Direction_6FFD93554112DE5A9819B4B3F957D58D; // 0x0418(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_419[0x7];                                      // 0x0419(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     DroneInOut;                                        // 0x0420(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void DismissDrone();
	void DroneInOut__FinishedFunc();
	void DroneInOut__UpdateFunc();
	void ExecuteUbergraph_BP_Drone(int32 EntryPoint);
	void IdleMove__FinishedFunc();
	void IdleMove__UpdateFunc();
	void OnCallDrone(bool bNewAdded);
	void ReceiveTick(float DeltaSeconds);
	void SetDroneMaterialReverse(bool bIsReverse);
	void SetDroneMaterials();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Drone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Drone_C")
	}
	static class ABP_Drone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Drone_C>();
	}
};
DUMPER7_ASSERTS_ABP_Drone_C;

SDK_NAMESPACE_END
