#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemWarpRingObject

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ItemWarpRingObject.BP_ItemWarpRingObject_C
// 0x0000 (0x0850 - 0x0850)
class ABP_ItemWarpRingObject_C final : public AItemWarpRingObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ItemWarpRingObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ItemWarpRingObject_C")
	}
	static class ABP_ItemWarpRingObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ItemWarpRingObject_C>();
	}
};
DUMPER7_ASSERTS_ABP_ItemWarpRingObject_C;

SDK_NAMESPACE_END
