#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemWeightObject

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ItemWeightObject.BP_ItemWeightObject_C
// 0x0000 (0x06C0 - 0x06C0)
class ABP_ItemWeightObject_C final : public AItemWeightObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ItemWeightObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ItemWeightObject_C")
	}
	static class ABP_ItemWeightObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ItemWeightObject_C>();
	}
};
DUMPER7_ASSERTS_ABP_ItemWeightObject_C;

SDK_NAMESPACE_END
