#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuRacerMachine

#include "Basic.hpp"

#include "UNION_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MenuRacerMachine.BP_MenuRacerMachine_C
// 0x0000 (0x0500 - 0x0500)
class ABP_MenuRacerMachine_C final : public AMenuRacerMachine
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MenuRacerMachine_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MenuRacerMachine_C")
	}
	static class ABP_MenuRacerMachine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MenuRacerMachine_C>();
	}
};
DUMPER7_ASSERTS_ABP_MenuRacerMachine_C;

SDK_NAMESPACE_END
