#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceSequence

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "UnionRun_structs.hpp"
#include "UnionUI_structs.hpp"
#include "UnionLib_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RaceSequence.BP_RaceSequence_C
// 0x0268 (0x06B0 - 0x0448)
class ABP_RaceSequence_C final : public ARaceSequence
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0448(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPC_RaceSequenceStateSave_C*           BPC_RaceSequenceStateSave;                         // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateDriverGetting_C*  BPC_RaceSequenceStateDriverGetting;                // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateTermination_C*    BPC_RaceSequenceStateTermination;                  // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_AppNet_C*                          BPC_AppNet;                                        // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateReadyParam_C*     BPC_RaceSequenceStateReadyParam;                   // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStatePauseMenu_C*      BPC_RaceSequenceStatePauseMenu;                    // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateRivalTeamEliminateResult_C* BPC_RaceSequenceStateRivalTeamEliminateResult; // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateSetupAssets_C*    BPC_RaceSequenceStateSetupAssets;                  // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateGadgetPlate_C*    BPC_RaceSequenceStateGadgetPlate;                  // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateSendRaceEnd_C*    BPC_RaceSequenceStateSendRaceEnd;                  // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateSendRaceStart_C*  BPC_RaceSequenceStateSendRaceStart;                // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_JudgeEndingState_C*                BPC_JudgeEndingState;                              // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateEnding_C*         BPC_RaceSequenceStateEnding;                       // 0x04B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateResultRival_C*    BPC_RaceSequenceStateResultRival;                  // 0x04B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateCeremony_C*       BPC_RaceSequenceStateCeremony;                     // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateSpawnRacer_C*     BPC_RaceSequenceStateSpawnRacer;                   // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateFeaturedRacer_C*  BPC_RaceSequenceStateFeaturedRacer;                // 0x04D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStatePerformRival_C*   BPC_RaceSequenceStatePerformRival;                 // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateEntryRival_C*     BPC_RaceSequenceStateEntryRival;                   // 0x04E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateEntryRacer_C*     BPC_RaceSequenceStateEntryRacer;                   // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateIntroduceCourse_C* BPC_RaceSequenceStateIntroduceCourse;             // 0x04F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateEndMenu_C*        BPC_RaceSequenceStateEndMenu;                      // 0x04F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateResult_C*         BPC_RaceSequenceStateResult;                       // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateGoal_C*           BPC_RaceSequenceStateGoal;                         // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateDrive_C*          BPC_RaceSequenceStateDrive;                        // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateReady_C*          BPC_RaceSeuqneceStateReady;                        // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateCreateRace_C*     BPC_RaceSequenceStateCreateRace;                   // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_RaceSequenceStateLoadAssets_C*     BPC_RaceSequenceStateLoadAssets;                   // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWBP_System_Loading_BG_C*               LoadingWidget;                                     // 0x0530(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           BgmHandle;                                         // 0x0538(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         PlayerCount;                                       // 0x053C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NowDomainIndex;                                    // 0x0540(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NowLapCount;                                       // 0x0544(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RacerCount;                                        // 0x0548(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bLocalPlayerFirstGoal;                             // 0x054C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EViewSplitMode                                SplitMode;                                         // 0x054D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54E[0x2];                                      // 0x054E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BGMName;                                           // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	struct FSoundHandle                           SilenceSoundHandle;                                // 0x0560(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         NowDomainNumber;                                   // 0x0564(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonRaceMenuContentId                      RaceEndMenuContentId;                              // 0x0568(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnded;                                            // 0x0569(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_56A[0x6];                                      // 0x056A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, class FString>            BGMNameMap;                                        // 0x0570(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 BGMNameWork;                                       // 0x05C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class ARaceStandings*                         LoadingRaceStandings;                              // 0x05D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<int32>                                 OverrideDriverIds;                                 // 0x05D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bOverrideDriverId;                                 // 0x05E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5E9[0x7];                                      // 0x05E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, struct FRaceCourseMapInfo>        DomainIndex_MapTexture;                            // 0x05F0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FRaceCourseSubMapInfo>          RaceCourseSubMapInfo;                              // 0x0640(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TSoftClassPtr<class UClass>                   LoadingRaceStandingsClassRef;                      // 0x0650(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UClass*                                 As_Race_Standings;                                 // 0x0678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           RaceSilenceSoundHandle;                            // 0x0680(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance)
	uint8                                         Pad_684[0x4];                                      // 0x0684(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UObject*>                        CharaIcons;                                        // 0x0688(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Tmp;                                               // 0x0698(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69C[0x4];                                      // 0x069C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 LoadRaceEndMenuSequence;                           // 0x06A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UWBP_System_BlackBoard_C*               BlackBoard;                                        // 0x06A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AfterReadyStatusObject();
	void ApplyOnlineCharaMachineSetting();
	void ApplyParam(class UUnionRacers* Racers_0, int32 RacerIndex);
	void ApplyParamIF();
	void BGMInit();
	void BindRaceBGMEvent(class UAppRaceEventManager* AppRaceEventManager);
	void BindSilenceSoundEvent(class UAppRaceEventManager* AppRaceEventManager);
	void ChangeDomainPre1st(int32 RacerIndex);
	void ChangeSubEvent(const EMainSubCourseIndex& NextMainSubState, int32 RacerID);
	void ChangeSubMapTexture(int32 DomainIndex, EMainSubCourseIndex NextMainSubState, EStageCourseMainSubMapInfo* MainSubState);
	void Chara_Machine_COMROM();
	void CheckDebugGenericVar();
	void ConvertIndexToDriverId(int32 Index_0, EDriverId* ID);
	void ConvertIndexToPre1stBehaviorId(int32 Index_0, int32* ID);
	void DebugOverride();
	void ExecuteUbergraph_BP_RaceSequence(int32 EntryPoint);
	void FinishExitFade(EUnionUIFadeDirection FadeDirection);
	void GetBGMNameFromLevel(bool IsIntro, class FString* BGMName_0);
	void GetFooter(class UWBP_FooterMenu_C** FooterMenu_0, bool* IsValid);
	void GetMovieSkipDelaySeconds(double* Seconds);
	void GetRaceBGMLabel(bool IsIntro, class FString* Label);
	void GetRaceEndMenuContentId(ECommonRaceMenuContentId* RaceEndMenuContentId_0);
	void HideBlackBoard(double Delay);
	void HideLoadingWidget();
	void HideRaceStandings();
	void IsOnCourseEditor(bool* Retval);
	void KE_MonsterTruck(int32 RacerIndex);
	void KE_YellowDrill(int32 RacerIndex);
	void OnFinalize();
	void OnInitialize();
	void OnInitStateExit();
	void OnInitStateIdle();
	void OnLoaded_15D3E10346BF46B1108571972800063D(TSubclassOf<class UObject> Loaded);
	void OnLoaded_3C57416242996D342FC890B6D0586604(class UObject* Loaded);
	void OnLoaded_9588B33D4EB8ABB3F49B76B997068961(TSubclassOf<class UObject> Loaded);
	void OnLoaded_F85D0A1C4A57623E131AA8A4E3643AF2(TSubclassOf<class UObject> Loaded);
	void OnReadyBeforeCount();
	void Play_BGM(class USoundAtomCue* Sound);
	void RaceBGMFinished();
	void RaceBGMonCourseEditor(bool FinalLap);
	void RaceDecideTravelRingGate(const class FString& Value, bool bRandomCourse);
	void RaceFinalLapLast();
	void RaceGoalWithParam(struct FAppRaceEventGoalData& GoalParam);
	void RacePassedToFinalLapForce(const class FString& Value, const class FString& Value2);
	void RacePassedToFirstLap(const class FString& Value, const class FString& Value2);
	void RacePassedToFirstLapWhenAnotherTimeTrial();
	void RacePassedToPreFirstLapWhenAnotherTimeTrial(const class FString& Value);
	void RacePassedToSecondLap(bool bRandomCourse);
	void RacePassedToSecondLapForce(const class FString& Value, const class FString& Value2);
	void RaceReturnFromDomainSubInFinalLap();
	void RaceReturnFromDomainSubInFirstLap();
	void RaceReturnFromDomainSubInSecondLap();
	void RacerInit(int32 RacerIndex, int32 PlayerIndex, bool bLocalPlayer, ERacerControlType ControlType, class APawn*& Vehicle, class UUnionRacers*& Racers_0, class UUnionRacerStatusObject** OutputPin);
	void RaceSelectTravelRingGate();
	void RaceSetAisacRingGateDistanceFirstLapToSecondLap(float Value);
	void RaceSetAisacRingGateDistanceSecondLapToFinalLap(float Value);
	void RaceSetBGMNameFirstLap(const class FString& Value);
	void RaceTransitionToDomainSubInFinalLap();
	void RaceTransitionToDomainSubInFirstLap();
	void RaceTransitionToDomainSubInSecondLap();
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void RecePassedToFinalLap(const class FString& Value);
	void RecePassedToFinalLapWhenTimeTrial(const class FString& Value);
	void RefreshHUD();
	void RemoveFooter();
	void Select_Course_Setting_Impl(TSoftObjectPtr<class UObject>* Texture, double* OrthoRate, double* Angle, struct FVector* Offset);
	void SelectCourseSetting(TSoftObjectPtr<class UObject>* Texture, float* OrthoRate, float* Angle, struct FVector* Offset);
	void Set_BGMName(bool bMainCourse, const class FString& InBGMName, class FString* OutBGMName);
	void SetCourseMapSetting(int32 DomainIndex, const struct FRaceCourseMapInfo& MapInfo);
	void SetCourseSubMapSetting(int32 DomainIndex, const struct FRaceCourseSubMapInfo& MapInfo);
	void SetEnableRaceSilenceSound(bool Enable);
	void SetEnableResultSilenceSound(bool Enable);
	void SetEnableSilenceSound(bool bEnable);
	void SetLoadingPhase(EUnionLoadingGaugeState LoadingGaurgeState);
	void SetRaceBGMVolume(double Volume);
	void SetRaceEndMenuContentId(ECommonRaceMenuContentId CommonRaceMenuContentId);
	void Show_Race_Standings();
	void Show_Race_Standings_Impl();
	void ShowLoadingWidget();
	void SpawnMachine(int32 InRacerIndex, int32 InPlayerIndex, bool* bCar, class APawn** AsPawn);
	void StatusObjectEventInt(const int32& EventId, const int32& Value);
	void StopBGM();
	void StopRaceBGM();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RaceSequence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RaceSequence_C")
	}
	static class ABP_RaceSequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RaceSequence_C>();
	}
};
DUMPER7_ASSERTS_ABP_RaceSequence_C;

SDK_NAMESPACE_END
