#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_MenuSubStateSelectClass

#include "Basic.hpp"

#include "BPC_MenuSubStateSelectClass_classes.hpp"
#include "BPC_MenuSubStateSelectClass_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C. OnSpecialPressedEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::_OnSpecialPressedEvent_Event(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", " OnSpecialPressedEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C__OnSpecialPressedEvent_Event Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.CloseSubCommand
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::CloseSubCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "CloseSubCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.ConvertClassIdToIndex
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESpeedClassId                           ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Index_0                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::ConvertClassIdToIndex(ESpeedClassId ID, int32* Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "ConvertClassIdToIndex");

	Params::BPC_MenuSubStateSelectClass_C_ConvertClassIdToIndex Parms{};

	Parms.ID = ID;

	UObject::ProcessEvent(Func, &Parms);

	if (Index_0 != nullptr)
		*Index_0 = Parms.Index_0;
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.ConvertIndexToClassId
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EMenuSpeedClassId*                      MenuSpeedClass                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::ConvertIndexToClassId(int32 Index_0, EMenuSpeedClassId* MenuSpeedClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "ConvertIndexToClassId");

	Params::BPC_MenuSubStateSelectClass_C_ConvertIndexToClassId Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (MenuSpeedClass != nullptr)
		*MenuSpeedClass = Parms.MenuSpeedClass;
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::CustomEvent_0(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "CustomEvent_0");

	Params::BPC_MenuSubStateSelectClass_C_CustomEvent_0 Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.DestroyPlayer
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::DestroyPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "DestroyPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.ExecuteUbergraph_BPC_MenuSubStateSelectClass
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::ExecuteUbergraph_BPC_MenuSubStateSelectClass(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "ExecuteUbergraph_BPC_MenuSubStateSelectClass");

	Params::BPC_MenuSubStateSelectClass_C_ExecuteUbergraph_BPC_MenuSubStateSelectClass Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.GetLastStateIsClassSelect
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   LClassSelect                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::GetLastStateIsClassSelect(bool* LClassSelect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "GetLastStateIsClassSelect");

	Params::BPC_MenuSubStateSelectClass_C_GetLastStateIsClassSelect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (LClassSelect != nullptr)
		*LClassSelect = Parms.LClassSelect;
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.InitSubCommand
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::InitSubCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "InitSubCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnCancel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnCancel(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnCancel");

	Params::BPC_MenuSubStateSelectClass_C_OnCancel Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnClassSelectIn
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnClassSelectIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnClassSelectIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnDecideClassSelectScene
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnDecideClassSelectScene(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnDecideClassSelectScene");

	Params::BPC_MenuSubStateSelectClass_C_OnDecideClassSelectScene Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnExitState
// (Event, Public, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnExitState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnExitState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnInitState
// (Event, Public, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnInitState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnInitState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnLeftShoulderPressedEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnLeftShoulderPressedEvent_Event(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnLeftShoulderPressedEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C_OnLeftShoulderPressedEvent_Event Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnLeftShoulderReleasedEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnLeftShoulderReleasedEvent_Event(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnLeftShoulderReleasedEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C_OnLeftShoulderReleasedEvent_Event Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnLoaded_34F2760D430D7D602227CAA2E60109C4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UObject>              Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnLoaded_34F2760D430D7D602227CAA2E60109C4(TSubclassOf<class UObject> Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnLoaded_34F2760D430D7D602227CAA2E60109C4");

	Params::BPC_MenuSubStateSelectClass_C_OnLoaded_34F2760D430D7D602227CAA2E60109C4 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnLoaded_C245C939437FB5BD9D84E8966E301E25
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UObject>              Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnLoaded_C245C939437FB5BD9D84E8966E301E25(TSubclassOf<class UObject> Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnLoaded_C245C939437FB5BD9D84E8966E301E25");

	Params::BPC_MenuSubStateSelectClass_C_OnLoaded_C245C939437FB5BD9D84E8966E301E25 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnNextSequence
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnNextSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnNextSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnOutAnimFinished
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnOutAnimFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnOutAnimFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnOutFinished_PrevSequence
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnOutFinished_PrevSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnOutFinished_PrevSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnPrevSequence
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::OnPrevSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnPrevSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnRightShoulderPressedEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnRightShoulderPressedEvent_Event(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnRightShoulderPressedEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C_OnRightShoulderPressedEvent_Event Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnRightShoulderReleasedEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnRightShoulderReleasedEvent_Event(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnRightShoulderReleasedEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C_OnRightShoulderReleasedEvent_Event Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnUISceneFocusEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnUISceneFocusEvent_Event(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnUISceneFocusEvent_Event");

	Params::BPC_MenuSubStateSelectClass_C_OnUISceneFocusEvent_Event Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.OnUpdateState
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::OnUpdateState(float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "OnUpdateState");

	Params::BPC_MenuSubStateSelectClass_C_OnUpdateState Parms{};

	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.ShoulderButtonCheck
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::ShoulderButtonCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "ShoulderButtonCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.StartSelectClassState
// (BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::StartSelectClassState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "StartSelectClassState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.UIFadeWidget_OnFinishedFade
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EUnionUIFadeDirection                   FadeDirection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_MenuSubStateSelectClass_C::UIFadeWidget_OnFinishedFade(EUnionUIFadeDirection FadeDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "UIFadeWidget_OnFinishedFade");

	Params::BPC_MenuSubStateSelectClass_C_UIFadeWidget_OnFinishedFade Parms{};

	Parms.FadeDirection = FadeDirection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C.UnbindAllEvents
// (Public, BlueprintCallable, BlueprintEvent)

void UBPC_MenuSubStateSelectClass_C::UnbindAllEvents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_MenuSubStateSelectClass_C", "UnbindAllEvents");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
