#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_PlayerProfile

#include "Basic.hpp"

#include "BPC_PlayerProfile_classes.hpp"
#include "BPC_PlayerProfile_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_PlayerProfile.BPC_PlayerProfile_C.ExecuteUbergraph_BPC_PlayerProfile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_PlayerProfile_C::ExecuteUbergraph_BPC_PlayerProfile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "ExecuteUbergraph_BPC_PlayerProfile");

	Params::BPC_PlayerProfile_C_ExecuteUbergraph_BPC_PlayerProfile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnDetailAnimEndEvent
// (BlueprintCallable, BlueprintEvent)

void UBPC_PlayerProfile_C::OnDetailAnimEndEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnDetailAnimEndEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnInitState
// (Event, Public, BlueprintEvent)

void UBPC_PlayerProfile_C::OnInitState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnInitState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnPlayerProfileCameraMoveEndEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// ELobbyCameraMoveType                    MoveType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_PlayerProfile_C::OnPlayerProfileCameraMoveEndEvent(ELobbyCameraMoveType MoveType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnPlayerProfileCameraMoveEndEvent");

	Params::BPC_PlayerProfile_C_OnPlayerProfileCameraMoveEndEvent Parms{};

	Parms.MoveType = MoveType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnPressedCancel
// (BlueprintCallable, BlueprintEvent)

void UBPC_PlayerProfile_C::OnPressedCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnPressedCancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnPressedNextPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsLeftInput                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_PlayerProfile_C::OnPressedNextPlayer(bool bIsLeftInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnPressedNextPlayer");

	Params::BPC_PlayerProfile_C_OnPressedNextPlayer Parms{};

	Parms.bIsLeftInput = bIsLeftInput;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.OnPressedNice
// (BlueprintCallable, BlueprintEvent)

void UBPC_PlayerProfile_C::OnPressedNice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "OnPressedNice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_PlayerProfile.BPC_PlayerProfile_C.SetNextMenuSequenceSubState
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EMenuSequenceSubState                   InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_PlayerProfile_C::SetNextMenuSequenceSubState(EMenuSequenceSubState InState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_PlayerProfile_C", "SetNextMenuSequenceSubState");

	Params::BPC_PlayerProfile_C_SetNextMenuSequenceSubState Parms{};

	Parms.InState = InState;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
