#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_TimeTrialLoginState

#include "Basic.hpp"

#include "BPC_TimeTrialLoginState_classes.hpp"
#include "BPC_TimeTrialLoginState_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.CreateErrorPopup
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      MessegeText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UBPC_TimeTrialLoginState_C::CreateErrorPopup(const class FText& MessegeText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "CreateErrorPopup");

	Params::BPC_TimeTrialLoginState_C_CreateErrorPopup Parms{};

	Parms.MessegeText = std::move(MessegeText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.CreateTryLoginPopup
// (BlueprintCallable, BlueprintEvent)

void UBPC_TimeTrialLoginState_C::CreateTryLoginPopup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "CreateTryLoginPopup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.ExecuteUbergraph_BPC_TimeTrialLoginState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_TimeTrialLoginState_C::ExecuteUbergraph_BPC_TimeTrialLoginState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "ExecuteUbergraph_BPC_TimeTrialLoginState");

	Params::BPC_TimeTrialLoginState_C_ExecuteUbergraph_BPC_TimeTrialLoginState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.OnDecideError
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_TimeTrialLoginState_C::OnDecideError(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "OnDecideError");

	Params::BPC_TimeTrialLoginState_C_OnDecideError Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.OnExitState
// (Event, Public, BlueprintEvent)

void UBPC_TimeTrialLoginState_C::OnExitState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "OnExitState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.OnInitState
// (Event, Public, BlueprintEvent)

void UBPC_TimeTrialLoginState_C::OnInitState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "OnInitState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.OnLogin
// (BlueprintCallable, BlueprintEvent)

void UBPC_TimeTrialLoginState_C::OnLogin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "OnLogin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.OnLoginResult_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSuccess                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsEnableOnlinePlay                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsRequestedSequenceBlock                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_TimeTrialLoginState_C::OnLoginResult_Event(bool IsSuccess, bool bIsEnableOnlinePlay, bool IsRequestedSequenceBlock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "OnLoginResult_Event");

	Params::BPC_TimeTrialLoginState_C_OnLoginResult_Event Parms{};

	Parms.IsSuccess = IsSuccess;
	Parms.bIsEnableOnlinePlay = bIsEnableOnlinePlay;
	Parms.IsRequestedSequenceBlock = IsRequestedSequenceBlock;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_TimeTrialLoginState.BPC_TimeTrialLoginState_C.TryLoginOnDecide_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_TimeTrialLoginState_C::TryLoginOnDecide_Event(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_TimeTrialLoginState_C", "TryLoginOnDecide_Event");

	Params::BPC_TimeTrialLoginState_C_TryLoginOnDecide_Event Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
