#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CR_Cockpit_Sus

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ControlRig_classes.hpp"


SDK_NAMESPACE_START

// ControlRigBlueprintGeneratedClass CR_Cockpit_Sus.CR_Cockpit_Sus_C
// 0x0018 (0x0AC0 - 0x0AA8)
class UCR_Cockpit_Sus_C final : public UControlRig
{
public:
	TArray<struct FVector>                        WheelPos;                                          // 0x0AA8(0x0010)(Edit, BlueprintVisible)
	bool                                          IsEnableWheelUpdate;                               // 0x0AB8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CR_Cockpit_Sus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CR_Cockpit_Sus_C")
	}
	static class UCR_Cockpit_Sus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCR_Cockpit_Sus_C>();
	}
};
DUMPER7_ASSERTS_UCR_Cockpit_Sus_C;

SDK_NAMESPACE_END
