#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_RivalResult_Car_N

#include "Basic.hpp"

#include "LS_RivalResult_Car_N_classes.hpp"
#include "LS_RivalResult_Car_N_parameters.hpp"


SDK_NAMESPACE_START

// Function LS_RivalResult_Car_N.LS_RivalResult_Car_N_DirectorBP_C.ExecuteUbergraph_LS_RivalResult_Car_N_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_RivalResult_Car_N_DirectorBP_C::ExecuteUbergraph_LS_RivalResult_Car_N_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_RivalResult_Car_N_DirectorBP_C", "ExecuteUbergraph_LS_RivalResult_Car_N_DirectorBP");

	Params::LS_RivalResult_Car_N_DirectorBP_C_ExecuteUbergraph_LS_RivalResult_Car_N_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_RivalResult_Car_N.LS_RivalResult_Car_N_DirectorBP_C.OnCreated
// (Event, Public, BlueprintEvent)

void ULS_RivalResult_Car_N_DirectorBP_C::OnCreated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_RivalResult_Car_N_DirectorBP_C", "OnCreated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_RivalResult_Car_N.LS_RivalResult_Car_N_DirectorBP_C.OnPauseScene
// (BlueprintCallable, BlueprintEvent)

void ULS_RivalResult_Car_N_DirectorBP_C::OnPauseScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_RivalResult_Car_N_DirectorBP_C", "OnPauseScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_RivalResult_Car_N.LS_RivalResult_Car_N_DirectorBP_C.OnSlideScreen
// (BlueprintCallable, BlueprintEvent)

void ULS_RivalResult_Car_N_DirectorBP_C::OnSlideScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_RivalResult_Car_N_DirectorBP_C", "OnSlideScreen");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
