#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCustom_Sub_Parts

#include "Basic.hpp"

#include "WBP_MachineCustom_Sub_Parts_classes.hpp"
#include "WBP_MachineCustom_Sub_Parts_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MachineCustom_Sub_Parts.WBP_MachineCustom_Sub_Parts_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MachineCustom_Sub_Parts_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineCustom_Sub_Parts_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MachineCustom_Sub_Parts.WBP_MachineCustom_Sub_Parts_C.ExecuteUbergraph_WBP_MachineCustom_Sub_Parts
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MachineCustom_Sub_Parts_C::ExecuteUbergraph_WBP_MachineCustom_Sub_Parts(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineCustom_Sub_Parts_C", "ExecuteUbergraph_WBP_MachineCustom_Sub_Parts");

	Params::WBP_MachineCustom_Sub_Parts_C_ExecuteUbergraph_WBP_MachineCustom_Sub_Parts Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MachineCustom_Sub_Parts.WBP_MachineCustom_Sub_Parts_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MachineCustom_Sub_Parts_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineCustom_Sub_Parts_C", "PreConstruct");

	Params::WBP_MachineCustom_Sub_Parts_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MachineCustom_Sub_Parts.WBP_MachineCustom_Sub_Parts_C.OnCreateRewardDialog
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class URewardDialog*                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class URewardDialog* UWBP_MachineCustom_Sub_Parts_C::OnCreateRewardDialog() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineCustom_Sub_Parts_C", "OnCreateRewardDialog");

	Params::WBP_MachineCustom_Sub_Parts_C_OnCreateRewardDialog Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
