#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_PartsScrollBox_W

#include "Basic.hpp"

#include "UNION_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MachineSelect_Sub_PartsScrollBox_W.WBP_MachineSelect_Sub_PartsScrollBox_W_C
// 0x0008 (0x0398 - 0x0390)
class UWBP_MachineSelect_Sub_PartsScrollBox_W_C final : public UMachinePartsScrollBox
{
public:
	class UImage*                                 Side_Shadow;                                       // 0x0390(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PlaySoundImpossible();
	void PlaySoundPossible();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineSelect_Sub_PartsScrollBox_W_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineSelect_Sub_PartsScrollBox_W_C")
	}
	static class UWBP_MachineSelect_Sub_PartsScrollBox_W_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineSelect_Sub_PartsScrollBox_W_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineSelect_Sub_PartsScrollBox_W_C;

SDK_NAMESPACE_END
