#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GrandPrix_SpeechBelt

#include "Basic.hpp"

#include "WBP_GrandPrix_SpeechBelt_classes.hpp"
#include "WBP_GrandPrix_SpeechBelt_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_GrandPrix_SpeechBelt.WBP_GrandPrix_SpeechBelt_C.CloseMessageSpeechArrow
// (BlueprintCallable, BlueprintEvent)

void UWBP_GrandPrix_SpeechBelt_C::CloseMessageSpeechArrow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrandPrix_SpeechBelt_C", "CloseMessageSpeechArrow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GrandPrix_SpeechBelt.WBP_GrandPrix_SpeechBelt_C.ExecuteUbergraph_WBP_GrandPrix_SpeechBelt
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GrandPrix_SpeechBelt_C::ExecuteUbergraph_WBP_GrandPrix_SpeechBelt(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrandPrix_SpeechBelt_C", "ExecuteUbergraph_WBP_GrandPrix_SpeechBelt");

	Params::WBP_GrandPrix_SpeechBelt_C_ExecuteUbergraph_WBP_GrandPrix_SpeechBelt Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GrandPrix_SpeechBelt.WBP_GrandPrix_SpeechBelt_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GrandPrix_SpeechBelt_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrandPrix_SpeechBelt_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GrandPrix_SpeechBelt.WBP_GrandPrix_SpeechBelt_C.SetMessageSpeechArrow
// (BlueprintCallable, BlueprintEvent)

void UWBP_GrandPrix_SpeechBelt_C::SetMessageSpeechArrow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GrandPrix_SpeechBelt_C", "SetMessageSpeechArrow");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
