#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachinrCustom_Sub_Paint_PresetWindow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionUI_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MachinrCustom_Sub_Paint_PresetWindow.WBP_MachinrCustom_Sub_Paint_PresetWindow_C
// 0x0050 (0x0330 - 0x02E0)
class UWBP_MachinrCustom_Sub_Paint_PresetWindow_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWrapBox*                               WrapBox;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionUIButtonsPanel*                   ButtonsPanel;                                      // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UUnionUIGridNavigationBuilder*          GridNavigationBuilder;                             // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         ItemNumInRow;                                      // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnItemFocused;                                     // 0x0308(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(EUnionUIControlDir Direction, class UUnionUIButtonBase* Button, int32 RowIndex, int32 ColumnIndex)> OnSideNavigationCustom; // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         LastSelectedIndex;                                 // 0x0328(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BuildNavigation(bool bInWrapLeftRight, bool IsSimpleCustom);
	void Construct();
	void Decision(class UUnionUIButtonBase* InButton);
	void Event_OnFocused(class UUnionUIButtonBase* Button);
	void Event_OnSideNavigationCustom(EUnionUIControlDir InDirection, class UUnionUIButtonBase* InButton, int32 InRowIndex, int32 InColumnIndex);
	void ExecuteUbergraph_WBP_MachinrCustom_Sub_Paint_PresetWindow(int32 EntryPoint);
	void HideCursor();
	void HideTextBalloon();
	void SetButtonsPanel(class UUnionUIButtonsPanel* InButtonsPanel);
	void SetItems(TArray<struct FST_ColorPresetSelectPageItemData>& InItemDataList);
	void SetItemsPlayerIndex(int32 InPlayerIndex);
	void SetupItems();

	void GetItem(int32 InIndex, class UWBP_MachinrCustom_Sub_Paint_PresetIcon_C** Output) const;
	void GetItemNumInRow(int32* OutItemNumInRow) const;
	void GetItems(TArray<class UWBP_MachinrCustom_Sub_Paint_PresetIcon_C*>* list) const;
	void GetLastSelectedIndex(int32* LastSelectedIndex_0) const;
	void GetNavigation(class UUnionUIGridNavigationBuilder** GridNavigationBuilder_0) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachinrCustom_Sub_Paint_PresetWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachinrCustom_Sub_Paint_PresetWindow_C")
	}
	static class UWBP_MachinrCustom_Sub_Paint_PresetWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachinrCustom_Sub_Paint_PresetWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachinrCustom_Sub_Paint_PresetWindow_C;

SDK_NAMESPACE_END
