#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FooterMenu

#include "Basic.hpp"

#include "UNION_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_FooterMenu.WBP_FooterMenu_C.ExecuteUbergraph_WBP_FooterMenu
// 0x0230 (0x0230 - 0x0000)
struct WBP_FooterMenu_C_ExecuteUbergraph_WBP_FooterMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue;                 // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_1; // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_1;               // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_2; // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_2;               // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_3; // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_3;               // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_4; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_4;               // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_5; // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_5;               // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62[0x6];                                       // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_6; // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_6;               // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_72[0x6];                                       // 0x0072(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_7; // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_7;               // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_8; // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_8;               // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_9; // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_9;               // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A2[0x6];                                       // 0x00A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_10; // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_10;              // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_11; // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_11;              // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_12; // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_12;                    // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_13; // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_13;                    // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_12;              // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_13;              // 0x00E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E3[0x5];                                       // 0x00E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_14; // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_14;                    // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_FooterMenu_Sub_CommonBtn_C*        K2Node_DynamicCast_AsWBP_Footer_Menu_Sub_Common_Btn_15; // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_15;                    // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_14;              // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFooterInputType                              CallFunc_GetInputType_ReturnValue_15;              // 0x0102(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_103[0x5];                                      // 0x0103(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        K2Node_MakeArray_Array;                            // 0x0108(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_1;                          // 0x0118(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray;           // 0x0128(0x0010)(ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_1;         // 0x0138(0x0010)(ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_2;                          // 0x0148(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_3;                          // 0x0158(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_2;         // 0x0168(0x0010)(ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_3;         // 0x0178(0x0010)(ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_4;                          // 0x0188(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_5;                          // 0x0198(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_4;         // 0x01A8(0x0010)(ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_5;         // 0x01B8(0x0010)(ContainsInstancedReference)
	TArray<struct FFooterMenuWidgetArray>         K2Node_MakeArray_Array_6;                          // 0x01C8(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_7;                          // 0x01D8(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_6;         // 0x01E8(0x0010)(ContainsInstancedReference)
	TArray<class UWidget*>                        K2Node_MakeArray_Array_8;                          // 0x01F8(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FFooterMenuWidgetArray                 K2Node_MakeStruct_FooterMenuWidgetArray_7;         // 0x0208(0x0010)(ContainsInstancedReference)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0218(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FFooterMenuWidgetArray>         K2Node_MakeArray_Array_9;                          // 0x0220(0x0010)(ReferenceParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_WBP_FooterMenu_C_ExecuteUbergraph_WBP_FooterMenu;

// Function WBP_FooterMenu.WBP_FooterMenu_C.OnHovered
// 0x0018 (0x0018 - 0x0000)
struct WBP_FooterMenu_C_OnHovered final
{
public:
	class UButton*                                HoveredObject;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAppControllerInputManager*             CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAppPlayerController*                   CallFunc_GetPlayerController_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_FooterMenu_C_OnHovered;

// Function WBP_FooterMenu.WBP_FooterMenu_C.PlayAnimIn
// 0x0008 (0x0008 - 0x0000)
struct WBP_FooterMenu_C_PlayAnimIn final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_FooterMenu_C_PlayAnimIn;

// Function WBP_FooterMenu.WBP_FooterMenu_C.PlayAnimOut
// 0x0008 (0x0008 - 0x0000)
struct WBP_FooterMenu_C_PlayAnimOut final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_FooterMenu_C_PlayAnimOut;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
