#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_Ready

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"
#include "UnionUI_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MachineSelect_Sub_Ready.WBP_MachineSelect_Sub_Ready_C
// 0x0098 (0x0378 - 0x02E0)
class UWBP_MachineSelect_Sub_Ready_C final : public UReadyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Ready_Back;                                        // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ready_Loop;                                        // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ready_In;                                          // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 BG_Black;                                          // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RaceFlag;                                          // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionRichTextBlock*                    TXT_Ready;                                         // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 YellowLine_Center;                                 // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         CurrentIndex;                                      // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ReadyText;                                         // 0x0328(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FString                                 ReadyTextString;                                   // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              Event_AnimFinishedIn;                              // 0x0348(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              Event_AnimFinishedOut;                             // 0x0358(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FTimerHandle                           TimerHandle;                                       // 0x0368(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	EUnionUISceneAnimation                        PlayAnimType;                                      // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ClearText();
	void Construct();
	void ExecuteUbergraph_WBP_MachineSelect_Sub_Ready(int32 EntryPoint);
	void FireSceneAnim(EUnionUISceneAnimation AnimType);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void OneTextIn();
	void SetAnimationText(const class FText& ReadyText_0);
	void StartReadyAnimation();
	void TextReady(const class FString& Text);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineSelect_Sub_Ready_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineSelect_Sub_Ready_C")
	}
	static class UWBP_MachineSelect_Sub_Ready_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineSelect_Sub_Ready_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineSelect_Sub_Ready_C;

SDK_NAMESPACE_END
