#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCustom_Top

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "EMachineCustomizeWindowId_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MachineCustom_Top.WBP_MachineCustom_Top_C
// 0x0038 (0x0328 - 0x02F0)
class UWBP_MachineCustom_Top_C final : public UMachineCustomTop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Panel;                                             // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_MachineCustom;                            // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CMN_GadgetCount_C*                 WBP_CMN_GadgetCount;                               // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MachineCustom_CMN_Window_C*        WBP_MachineCustom_CMN_Window;                      // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Window_MachineParameter_C*         WBP_Window_MachineParameter;                       // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_MachineCustom;                      // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BndEvt__WBP_MachineCustom_Top_WBP_MachineCustom_Sub_CurrentWindow_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_WBP_MachineCustom_Top(int32 EntryPoint);
	void GetParamWindow(class UCharaMachineParamWindow** OutParamWindow);
	void SetupDonpaTicket();
	void SetupMachineCustomizeTabWindow(bool IsShowDonpaTicket);
	void SetupMachineSelectWindow();
	void SetupOther();
	void SetVisibleDonpaTicket(bool IsVisible_0);
	void SetWindowGroupVisible(bool bInIsVisible);
	void SwitchWindow(EMachineCustomizeWindowId InWindowId);
	void UpdateDonpaTicket();

	class UMachineCustomCommonWindow* GetMachineCustomCommonWindow() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineCustom_Top_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineCustom_Top_C")
	}
	static class UWBP_MachineCustom_Top_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineCustom_Top_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineCustom_Top_C;

SDK_NAMESPACE_END
