#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCustom_Sub_ColorPicker_TextureText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MachineCustom_Sub_ColorPicker_TextureText.WBP_MachineCustom_Sub_ColorPicker_TextureText_C
// 0x0018 (0x02F8 - 0x02E0)
class UWBP_MachineCustom_Sub_ColorPicker_TextureText_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 DSP_Set_Icon;                                      // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionRichTextBlock*                    TXT_TextureName;                                   // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_MachineCustom_Sub_ColorPicker_TextureText(int32 EntryPoint);
	void SetSelectIconVisible(bool bInIsVisible);
	void SetSurfaceName(const class FText& InSurfaceName);
	void Setup(const struct FST_ColorDetailWindowSurfaceItemData& InItemData);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineCustom_Sub_ColorPicker_TextureText_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineCustom_Sub_ColorPicker_TextureText_C")
	}
	static class UWBP_MachineCustom_Sub_ColorPicker_TextureText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineCustom_Sub_ColorPicker_TextureText_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineCustom_Sub_ColorPicker_TextureText_C;

SDK_NAMESPACE_END
