#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FestaResult_ContributionRate

#include "Basic.hpp"

#include "WBP_FestaResult_ContributionRate_classes.hpp"
#include "WBP_FestaResult_ContributionRate_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.Close
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_ContributionRate_C::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "Close");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_FestaResult_ContributionRate_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.ExecuteUbergraph_WBP_FestaResult_ContributionRate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_ContributionRate_C::ExecuteUbergraph_WBP_FestaResult_ContributionRate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "ExecuteUbergraph_WBP_FestaResult_ContributionRate");

	Params::WBP_FestaResult_ContributionRate_C_ExecuteUbergraph_WBP_FestaResult_ContributionRate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.Open
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_ContributionRate_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_ContributionRate_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "PreConstruct");

	Params::WBP_FestaResult_ContributionRate_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_ContributionRate.WBP_FestaResult_ContributionRate_C.SetRacerDataAll
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FFestaRacerContribution>&list                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_FestaResult_ContributionRate_C::SetRacerDataAll(const TArray<struct FFestaRacerContribution>& list)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_ContributionRate_C", "SetRacerDataAll");

	Params::WBP_FestaResult_ContributionRate_C_SetRacerDataAll Parms{};

	Parms.list = std::move(list);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
