#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ClassSelect_Sub_Btn_Class

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "UnionUI_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.ExecuteUbergraph_WBP_ClassSelect_Sub_Btn_Class
// 0x00E0 (0x00E0 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_ExecuteUbergraph_WBP_ClassSelect_Sub_Btn_Class final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUnionUIButtonSoundSetting                    Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUnionUIButtonSoundSetting                    Temp_byte_Variable_1;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EButtonFocusType                              Temp_byte_Variable_4;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EButtonFocusType                              Temp_byte_Variable_5;                              // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             Temp_byte_Variable_8;                              // 0x000F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EButtonFocusType                              K2Node_Select_Default_1;                           // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UUnionUIButtonBaseCore* Button)> K2Node_CreateDelegate_OutputDelegate;      // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBaseCore* Button)> K2Node_CreateDelegate_OutputDelegate_1;    // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUnionUIButtonBaseCore* Button)> K2Node_CreateDelegate_OutputDelegate_2;    // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUnionUIButtonSoundSetting                    K2Node_Select_Default_2;                           // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bLock;                          // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_InComplete;                           // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Current;                        // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Max;                            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMenuSpeedClassId                             K2Node_Event_InMenuSpeedClass;                     // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52[0x2];                                       // 0x0052(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBaseCore*                 K2Node_CustomEvent_Button_2;                       // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUnionUIButtonBaseCore*                 K2Node_CustomEvent_Button_1;                       // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0068(0x0010)()
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0080(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_2;            // 0x0090(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_3;            // 0x00A0(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_4;            // 0x00B0(0x0010)()
	class UUnionUIButtonBaseCore*                 K2Node_CustomEvent_Button;                         // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Select_Default_4;                           // 0x00C8(0x0010)(ConstParm)
	int32                                         K2Node_CustomEvent_MedalCount;                     // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_MedalMax;                       // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_ExecuteUbergraph_WBP_ClassSelect_Sub_Btn_Class;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.OnDecidedEvent_Event
// 0x0008 (0x0008 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_OnDecidedEvent_Event final
{
public:
	class UUnionUIButtonBaseCore*                 Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_OnDecidedEvent_Event;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.OnDeselectedEvent_Event
// 0x0008 (0x0008 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_OnDeselectedEvent_Event final
{
public:
	class UUnionUIButtonBaseCore*                 Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_OnDeselectedEvent_Event;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.OnSelectedEvent_Event
// 0x0008 (0x0008 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_OnSelectedEvent_Event final
{
public:
	class UUnionUIButtonBaseCore*                 Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_OnSelectedEvent_Event;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_PreConstruct;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.SetComplete
// 0x0001 (0x0001 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_SetComplete final
{
public:
	bool                                          InComplete;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_SetComplete;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.SetCompleteCount
// 0x0008 (0x0008 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_SetCompleteCount final
{
public:
	int32                                         Current;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max;                                               // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_SetCompleteCount;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.SetLock
// 0x0001 (0x0001 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_SetLock final
{
public:
	bool                                          bLock;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_SetLock;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.SetMenuSpeedClass
// 0x0001 (0x0001 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_SetMenuSpeedClass final
{
public:
	EMenuSpeedClassId                             InMenuSpeedClass;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_SetMenuSpeedClass;

// Function WBP_ClassSelect_Sub_Btn_Class.WBP_ClassSelect_Sub_Btn_Class_C.SetTimeTrialMedalCount
// 0x0008 (0x0008 - 0x0000)
struct WBP_ClassSelect_Sub_Btn_Class_C_SetTimeTrialMedalCount final
{
public:
	int32                                         MedalCount;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MedalMax;                                          // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ClassSelect_Sub_Btn_Class_C_SetTimeTrialMedalCount;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
