#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ready_M4

#include "Basic.hpp"

#include "WBP_Ready_M4_classes.hpp"
#include "WBP_Ready_M4_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Ready_M4.WBP_Ready_M4_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Ready_M4_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Ready_M4_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.ExecuteUbergraph_WBP_Ready_M4
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_M4_C::ExecuteUbergraph_WBP_Ready_M4(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "ExecuteUbergraph_WBP_Ready_M4");

	Params::WBP_Ready_M4_C_ExecuteUbergraph_WBP_Ready_M4 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.GadgetIconMouseEnable
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_M4_C::GadgetIconMouseEnable(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "GadgetIconMouseEnable");

	Params::WBP_Ready_M4_C_GadgetIconMouseEnable Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.OnDecideGoAnimDinished
// (BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::OnDecideGoAnimDinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "OnDecideGoAnimDinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.PlayGoAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::PlayGoAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "PlayGoAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.PlayInAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::PlayInAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "PlayInAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.PlayOutAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::PlayOutAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "PlayOutAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_M4_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "PreConstruct");

	Params::WBP_Ready_M4_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.SetCollapse
// (BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::SetCollapse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "SetCollapse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.SetReadyColor
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsCheck                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_M4_C::SetReadyColor(bool bIsCheck)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "SetReadyColor");

	Params::WBP_Ready_M4_C_SetReadyColor Parms{};

	Parms.bIsCheck = bIsCheck;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.SetThreePersonMode
// (BlueprintCallable, BlueprintEvent)

void UWBP_Ready_M4_C::SetThreePersonMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "SetThreePersonMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.UpdateGadgetDetailWindowToSlotZero
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InPlayerIndex                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_M4_C::UpdateGadgetDetailWindowToSlotZero(const int32 InPlayerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "UpdateGadgetDetailWindowToSlotZero");

	Params::WBP_Ready_M4_C_UpdateGadgetDetailWindowToSlotZero Parms{};

	Parms.InPlayerIndex = InPlayerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.GetCharaMachineParamWindow
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TArray<class UCharaMachineParamWindow*>*OutCharaMachineParamWindows                            (Parm, OutParm, ContainsInstancedReference)

void UWBP_Ready_M4_C::GetCharaMachineParamWindow(TArray<class UCharaMachineParamWindow*>* OutCharaMachineParamWindows) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "GetCharaMachineParamWindow");

	Params::WBP_Ready_M4_C_GetCharaMachineParamWindow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutCharaMachineParamWindows != nullptr)
		*OutCharaMachineParamWindows = std::move(Parms.OutCharaMachineParamWindows);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.GetGadgetPlateWindows
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TArray<class UGadgetPlateWindow*>*      OutGadgetPlateWindows                                  (Parm, OutParm, ContainsInstancedReference)

void UWBP_Ready_M4_C::GetGadgetPlateWindows(TArray<class UGadgetPlateWindow*>* OutGadgetPlateWindows) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "GetGadgetPlateWindows");

	Params::WBP_Ready_M4_C_GetGadgetPlateWindows Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutGadgetPlateWindows != nullptr)
		*OutGadgetPlateWindows = std::move(Parms.OutGadgetPlateWindows);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.GetReadyOptions
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TArray<class UReadyOption*>*            OutReadyOptions                                        (Parm, OutParm, ContainsInstancedReference)

void UWBP_Ready_M4_C::GetReadyOptions(TArray<class UReadyOption*>* OutReadyOptions) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "GetReadyOptions");

	Params::WBP_Ready_M4_C_GetReadyOptions Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutReadyOptions != nullptr)
		*OutReadyOptions = std::move(Parms.OutReadyOptions);
}


// Function WBP_Ready_M4.WBP_Ready_M4_C.GetReadyWindowCharacterIcons
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TArray<class UReadyWindowCharacterIcon*>*OutReadyWindowCharacterIcons                           (Parm, OutParm, ContainsInstancedReference)

void UWBP_Ready_M4_C::GetReadyWindowCharacterIcons(TArray<class UReadyWindowCharacterIcon*>* OutReadyWindowCharacterIcons) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_M4_C", "GetReadyWindowCharacterIcons");

	Params::WBP_Ready_M4_C_GetReadyWindowCharacterIcons Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutReadyWindowCharacterIcons != nullptr)
		*OutReadyWindowCharacterIcons = std::move(Parms.OutReadyWindowCharacterIcons);
}


SDK_NAMESPACE_END
