#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ready_Sub_Decide

#include "Basic.hpp"

#include "WBP_Ready_Sub_Decide_classes.hpp"
#include "WBP_Ready_Sub_Decide_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Ready_Sub_Decide.WBP_Ready_Sub_Decide_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Ready_Sub_Decide_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_Sub_Decide_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_Sub_Decide.WBP_Ready_Sub_Decide_C.DecideAnimation
// (BlueprintCallable, BlueprintEvent)

void UWBP_Ready_Sub_Decide_C::DecideAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_Sub_Decide_C", "DecideAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_Sub_Decide.WBP_Ready_Sub_Decide_C.ExecuteUbergraph_WBP_Ready_Sub_Decide
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_Sub_Decide_C::ExecuteUbergraph_WBP_Ready_Sub_Decide(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_Sub_Decide_C", "ExecuteUbergraph_WBP_Ready_Sub_Decide");

	Params::WBP_Ready_Sub_Decide_C_ExecuteUbergraph_WBP_Ready_Sub_Decide Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Ready_Sub_Decide.WBP_Ready_Sub_Decide_C.OnDecideAnimationFinished
// (BlueprintCallable, BlueprintEvent)

void UWBP_Ready_Sub_Decide_C::OnDecideAnimationFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_Sub_Decide_C", "OnDecideAnimationFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Ready_Sub_Decide.WBP_Ready_Sub_Decide_C.OnVisibilityChangedEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Ready_Sub_Decide_C::OnVisibilityChangedEvent(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ready_Sub_Decide_C", "OnVisibilityChangedEvent");

	Params::WBP_Ready_Sub_Decide_C_OnVisibilityChangedEvent Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
