#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PartyRace_Sub_Option_SettingBtn

#include "Basic.hpp"

#include "WBP_PartyRace_Sub_Option_SettingBtn_classes.hpp"
#include "WBP_PartyRace_Sub_Option_SettingBtn_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.BndEvt__WBP_PartyRace_Sub_Option_SettingBtn_UnionUIButton_49_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::BndEvt__WBP_PartyRace_Sub_Option_SettingBtn_UnionUIButton_49_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "BndEvt__WBP_PartyRace_Sub_Option_SettingBtn_UnionUIButton_49_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.ChangeControllerType
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAppControllerInputType                 BeforeType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EAppControllerInputType                 AfterType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::ChangeControllerType(EAppControllerInputType BeforeType, EAppControllerInputType AfterType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "ChangeControllerType");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_ChangeControllerType Parms{};

	Parms.BeforeType = BeforeType;
	Parms.AfterType = AfterType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.ExecuteUbergraph_WBP_PartyRace_Sub_Option_SettingBtn
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::ExecuteUbergraph_WBP_PartyRace_Sub_Option_SettingBtn(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "ExecuteUbergraph_WBP_PartyRace_Sub_Option_SettingBtn");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_ExecuteUbergraph_WBP_PartyRace_Sub_Option_SettingBtn Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.ForceFocusOutBtnEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::ForceFocusOutBtnEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "ForceFocusOutBtnEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.GetCurrentInput
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAppControllerInputType                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EAppControllerInputType UWBP_PartyRace_Sub_Option_SettingBtn_C::GetCurrentInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "GetCurrentInput");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_GetCurrentInput Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.GetText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_PartyRace_Sub_Option_SettingBtn_C::GetText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "GetText");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnAcceptKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnAcceptKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnAcceptKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnAddedToFocusPath");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnBackKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnBackKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnBackKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnDownKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnDownKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnDownKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnFocusImpl
// (BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnFocusImpl()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnFocusImpl");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnLeftKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnLeftKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnLeftKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnRemovedFromFocusPath");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnRightKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnRightKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnRightKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.OnUpKeyPressed
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::OnUpKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "OnUpKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.PlayActive
// (BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::PlayActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "PlayActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.PlayNonActive
// (BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::PlayNonActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "PlayNonActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetButtonLineParent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PartyRace_Sub_Option_Line_C* Parent_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetButtonLineParent(class UWBP_PartyRace_Sub_Option_Line_C* Parent_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetButtonLineParent");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetButtonLineParent Parms{};

	Parms.Parent_0 = Parent_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetButtonVisibility
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetButtonVisibility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetButtonVisibility");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetButtonVisibility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetIgnoreVisible
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIgnore_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetIgnoreVisible(bool bIgnore_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetIgnoreVisible");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetIgnoreVisible Parms{};

	Parms.bIgnore_0 = bIgnore_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetIsButtonSelected
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetIsButtonSelected(bool IsSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetIsButtonSelected");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetIsButtonSelected Parms{};

	Parms.IsSelected_0 = IsSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetLineParent
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCustomRaceSubOptionSettingLine*  LineParent                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetLineParent(class UCustomRaceSubOptionSettingLine* LineParent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetLineParent");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetLineParent Parms{};

	Parms.LineParent = LineParent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::SetText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "SetText");

	Params::WBP_PartyRace_Sub_Option_SettingBtn_C_SetText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.UnfocusEventImpl
// (BlueprintCallable, BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::UnfocusEventImpl()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "UnfocusEventImpl");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.WidgetAnimationEvt_Btn_Active_Loop_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::WidgetAnimationEvt_Btn_Active_Loop_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "WidgetAnimationEvt_Btn_Active_Loop_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.WidgetAnimationEvt_Btn_NonActive_Loop_K2Node_WidgetAnimationEvent_2
// (BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::WidgetAnimationEvt_Btn_NonActive_Loop_K2Node_WidgetAnimationEvent_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "WidgetAnimationEvt_Btn_NonActive_Loop_K2Node_WidgetAnimationEvent_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PartyRace_Sub_Option_SettingBtn.WBP_PartyRace_Sub_Option_SettingBtn_C.WidgetAnimationEvt_Btn_Select_Loop_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void UWBP_PartyRace_Sub_Option_SettingBtn_C::WidgetAnimationEvt_Btn_Select_Loop_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PartyRace_Sub_Option_SettingBtn_C", "WidgetAnimationEvt_Btn_Select_Loop_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
