#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Race_StartText

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_Race_StartText.WBP_Race_StartText_C.ExecuteUbergraph_WBP_Race_StartText
// 0x0014 (0x0014 - 0x0000)
struct WBP_Race_StartText_C_ExecuteUbergraph_WBP_Race_StartText final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Race_StartText_C_ExecuteUbergraph_WBP_Race_StartText;

// Function WBP_Race_StartText.WBP_Race_StartText_C.FireAnim
// 0x0008 (0x0008 - 0x0000)
struct WBP_Race_StartText_C_FireAnim final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Race_StartText_C_FireAnim;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
