#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_PartsScrollBox_W

#include "Basic.hpp"

#include "WBP_MachineSelect_Sub_PartsScrollBox_W_classes.hpp"
#include "WBP_MachineSelect_Sub_PartsScrollBox_W_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MachineSelect_Sub_PartsScrollBox_W.WBP_MachineSelect_Sub_PartsScrollBox_W_C.PlaySoundImpossible
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MachineSelect_Sub_PartsScrollBox_W_C::PlaySoundImpossible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineSelect_Sub_PartsScrollBox_W_C", "PlaySoundImpossible");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MachineSelect_Sub_PartsScrollBox_W.WBP_MachineSelect_Sub_PartsScrollBox_W_C.PlaySoundPossible
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MachineSelect_Sub_PartsScrollBox_W_C::PlaySoundPossible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MachineSelect_Sub_PartsScrollBox_W_C", "PlaySoundPossible");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
